; Generated by krakenc — Kraken Self-Hosted Compiler
; Source: tests/test_operators.kr

target triple = "x86_64-unknown-linux-gnu"

declare i32 @puts(i8*)
declare i32 @printf(i8*, ...)
declare i64 @strlen(i8*)
declare i8* @malloc(i64)
declare void @free(i8*)
declare i8* @realloc(i8*, i64)
declare i8* @memcpy(i8*, i8*, i64)
declare i32 @memcmp(i8*, i8*, i64)
declare i8* @strcpy(i8*, i8*)
declare i8* @strcat(i8*, i8*)
declare i32 @strcmp(i8*, i8*)
declare i8* @strdup(i8*)
declare i32 @sprintf(i8*, i8*, ...)
declare i32 @snprintf(i8*, i64, i8*, ...)
declare void @exit(i32)
declare i32 @system(i8*)
declare i8* @kr_getenv(i8*)
declare i8* @fopen(i8*, i8*)
declare i32 @fclose(i8*)
declare i64 @fread(i8*, i64, i64, i8*)
declare i64 @fwrite(i8*, i64, i64, i8*)
declare i32 @fputs(i8*, i8*)
declare i64 @fseek(i8*, i64, i32)
declare i64 @ftell(i8*)
declare i64 @atol(i8*)
declare double @atof(i8*)
declare double @sqrt(double)
declare double @pow(double, double)
declare double @floor(double)
declare double @ceil(double)
declare double @fabs(double)

; Kraken runtime functions
declare i8* @kr_str_concat(i8*, i8*)
declare i64 @kr_strlen(i8*)
declare i8* @kr_fmt_int(i64)
declare i8* @kr_fmt_float(double)
declare i8* @kr_fmt_bool(i1)
declare i1 @kr_str_eq(i8*, i8*)
declare i1 @kr_str_ne(i8*, i8*)
declare i8* @kr_str_slice(i8*, i64, i64)
declare i64 @kr_str_index_of(i8*, i8*)
declare i1 @kr_str_contains(i8*, i8*)
declare i1 @kr_str_starts_with(i8*, i8*)
declare i1 @kr_str_ends_with(i8*, i8*)
declare i8* @kr_str_to_lower(i8*)
declare i8* @kr_str_to_upper(i8*)
declare i8* @kr_str_trim(i8*)
declare i64 @kr_str_len(i8*)
declare i8* @kr_str_replace(i8*, i8*, i8*)
declare i64 @kr_atoi(i8*)
declare double @kr_atof(i8*)
declare i8* @kr_from_cstr(i8*)
declare i8* @kr_cstr(i8*)
declare i8* @kr_vec_int_new()
declare void @kr_vec_int_free(i8*)
declare void @kr_vec_int_push(i8*, i64)
declare i64 @kr_vec_int_get(i8*, i64)
declare void @kr_vec_int_set(i8*, i64, i64)
declare i64 @kr_vec_int_len(i8*)
declare i8* @kr_vec_string_new()
declare void @kr_vec_string_free(i8*)
declare void @kr_vec_string_push(i8*, i8*)
declare i8* @kr_vec_string_get(i8*, i64)
declare void @kr_vec_string_set(i8*, i64, i8*)
declare i64 @kr_vec_string_len(i8*)
declare i8* @kr_map_string_string_new()
declare void @kr_map_string_string_free(i8*)
declare void @kr_map_string_string_set(i8*, i8*, i8*)
declare i8* @kr_map_string_string_get(i8*, i8*)
declare i1 @kr_map_string_string_has(i8*, i8*)
declare i8* @kr_map_string_int_new()
declare void @kr_map_string_int_free(i8*)
declare void @kr_map_string_int_set(i8*, i8*, i64)
declare i64 @kr_map_string_int_get(i8*, i8*)
declare i1 @kr_map_string_int_has(i8*, i8*)
declare i64 @kr_detect_host_os()
declare i64 @kr_detect_host_arch()
declare i8* @kr_file_read_string(i8*)
declare i8* @kr_str_split(i8*, i8*)
declare i8* @kr_str_join(i8*, i8*)
declare i64 @kr_str_char_at(i8*, i64)
declare i8* @kr_str_from_char_code(i64)

@.str_0 = private unnamed_addr constant [9 x i8] c"  PASS: \00"
@.str_1 = private unnamed_addr constant [9 x i8] c"  FAIL: \00"
@.str_2 = private unnamed_addr constant [11 x i8] c" expected=\00"
@.str_3 = private unnamed_addr constant [9 x i8] c" actual=\00"
@.str_4 = private unnamed_addr constant [9 x i8] c"  PASS: \00"
@.str_5 = private unnamed_addr constant [9 x i8] c"  FAIL: \00"
@.str_6 = private unnamed_addr constant [31 x i8] c"=== krakenc Operator Tests ===\00"
@.str_7 = private unnamed_addr constant [1 x i8] c"\00"
@.str_8 = private unnamed_addr constant [8 x i8] c"[Shift]\00"
@.str_9 = private unnamed_addr constant [5 x i8] c"1<<3\00"
@.str_10 = private unnamed_addr constant [6 x i8] c"16>>2\00"
@.str_11 = private unnamed_addr constant [7 x i8] c"255<<8\00"
@.str_12 = private unnamed_addr constant [8 x i8] c"1024>>5\00"
@.str_13 = private unnamed_addr constant [9 x i8] c"[Modulo]\00"
@.str_14 = private unnamed_addr constant [5 x i8] c"10%3\00"
@.str_15 = private unnamed_addr constant [4 x i8] c"7%2\00"
@.str_16 = private unnamed_addr constant [4 x i8] c"8%4\00"
@.str_17 = private unnamed_addr constant [5 x i8] c"15%7\00"
@.str_18 = private unnamed_addr constant [18 x i8] c"[Compound Assign]\00"
@.str_19 = private unnamed_addr constant [5 x i8] c"x+=5\00"
@.str_20 = private unnamed_addr constant [5 x i8] c"x-=3\00"
@.str_21 = private unnamed_addr constant [5 x i8] c"x*=2\00"
@.str_22 = private unnamed_addr constant [5 x i8] c"x/=4\00"
@.str_23 = private unnamed_addr constant [5 x i8] c"x%=4\00"
@.str_24 = private unnamed_addr constant [14 x i8] c"[Bitwise NOT]\00"
@.str_25 = private unnamed_addr constant [3 x i8] c"~0\00"
@.str_26 = private unnamed_addr constant [4 x i8] c"~~5\00"
@.str_27 = private unnamed_addr constant [14 x i8] c"[Unary Minus]\00"
@.str_28 = private unnamed_addr constant [6 x i8] c"-(-5)\00"
@.str_29 = private unnamed_addr constant [7 x i8] c"-(3+4)\00"
@.str_30 = private unnamed_addr constant [11 x i8] c"[Combined]\00"
@.str_31 = private unnamed_addr constant [9 x i8] c"(1<<4)|3\00"
@.str_32 = private unnamed_addr constant [15 x i8] c"(0xFF&0xF0)>>4\00"
@.str_33 = private unnamed_addr constant [6 x i8] c"5+3*2\00"
@.str_34 = private unnamed_addr constant [8 x i8] c"(5+3)*2\00"
@.str_35 = private unnamed_addr constant [18 x i8] c"[Shift + Compare]\00"
@.str_36 = private unnamed_addr constant [9 x i8] c"1<<3 > 5\00"
@.str_37 = private unnamed_addr constant [11 x i8] c"16>>2 == 4\00"
@.str_38 = private unnamed_addr constant [1 x i8] c"\00"
@.str_39 = private unnamed_addr constant [36 x i8] c"=== All operator tests complete ===\00"
define i64 @kr_assert_eq(i8* %label.arg, i64 %expected.arg, i64 %actual.arg) {
entry:
  %label = alloca i8*
  store i8* %label.arg, i8** %label
  %expected = alloca i64
  store i64 %expected.arg, i64* %expected
  %actual = alloca i64
  store i64 %actual.arg, i64* %actual
  %0 = load i64, i64* %expected
  %1 = load i64, i64* %actual
  %2 = icmp eq i64 %0, %1
  br i1 %2, label %then0, label %else1
then0:
  %3 = getelementptr [9 x i8], [9 x i8]* @.str_0, i32 0, i32 0
  %4 = load i8*, i8** %label
  %5 = call i8* @kr_str_concat(i8* %3, i8* %4)
  %6 = call i32 @puts(i8* %5)
  br label %merge2
else1:
  %7 = getelementptr [9 x i8], [9 x i8]* @.str_1, i32 0, i32 0
  %8 = load i8*, i8** %label
  %9 = getelementptr [11 x i8], [11 x i8]* @.str_2, i32 0, i32 0
  %10 = load i64, i64* %expected
  %11 = call i8* @kr_fmt_int(i64 %10)
  %12 = getelementptr [9 x i8], [9 x i8]* @.str_3, i32 0, i32 0
  %13 = load i64, i64* %actual
  %14 = call i8* @kr_fmt_int(i64 %13)
  %15 = call i8* @kr_str_concat(i8* %12, i8* %14)
  %16 = call i8* @kr_str_concat(i8* %11, i8* %15)
  %17 = call i8* @kr_str_concat(i8* %9, i8* %16)
  %18 = call i8* @kr_str_concat(i8* %8, i8* %17)
  %19 = call i8* @kr_str_concat(i8* %7, i8* %18)
  %20 = call i32 @puts(i8* %19)
  br label %merge2
merge2:
  ret i64 0
}

define i64 @kr_assert_true(i8* %label.arg, i1 %value.arg) {
entry:
  %label = alloca i8*
  store i8* %label.arg, i8** %label
  %value = alloca i1
  store i1 %value.arg, i1* %value
  %0 = load i1, i1* %value
  br i1 %0, label %then0, label %else1
then0:
  %1 = getelementptr [9 x i8], [9 x i8]* @.str_4, i32 0, i32 0
  %2 = load i8*, i8** %label
  %3 = call i8* @kr_str_concat(i8* %1, i8* %2)
  %4 = call i32 @puts(i8* %3)
  br label %merge2
else1:
  %5 = getelementptr [9 x i8], [9 x i8]* @.str_5, i32 0, i32 0
  %6 = load i8*, i8** %label
  %7 = call i8* @kr_str_concat(i8* %5, i8* %6)
  %8 = call i32 @puts(i8* %7)
  br label %merge2
merge2:
  ret i64 0
}

define i64 @main() {
entry:
  %x = alloca i64
  %mask = alloca i64
  %0 = getelementptr [31 x i8], [31 x i8]* @.str_6, i32 0, i32 0
  %1 = call i32 @puts(i8* %0)
  %2 = getelementptr [1 x i8], [1 x i8]* @.str_7, i32 0, i32 0
  %3 = call i32 @puts(i8* %2)
  %4 = getelementptr [8 x i8], [8 x i8]* @.str_8, i32 0, i32 0
  %5 = call i32 @puts(i8* %4)
  %6 = getelementptr [5 x i8], [5 x i8]* @.str_9, i32 0, i32 0
  %7 = shl i64 1, 3
  %8 = call i64 @kr_assert_eq(i8* %6, i64 8, i64 %7)
  %9 = getelementptr [6 x i8], [6 x i8]* @.str_10, i32 0, i32 0
  %10 = ashr i64 16, 2
  %11 = call i64 @kr_assert_eq(i8* %9, i64 4, i64 %10)
  %12 = getelementptr [7 x i8], [7 x i8]* @.str_11, i32 0, i32 0
  %13 = shl i64 255, 8
  %14 = call i64 @kr_assert_eq(i8* %12, i64 65280, i64 %13)
  %15 = getelementptr [8 x i8], [8 x i8]* @.str_12, i32 0, i32 0
  %16 = ashr i64 1024, 5
  %17 = call i64 @kr_assert_eq(i8* %15, i64 32, i64 %16)
  %18 = getelementptr [9 x i8], [9 x i8]* @.str_13, i32 0, i32 0
  %19 = call i32 @puts(i8* %18)
  %20 = getelementptr [5 x i8], [5 x i8]* @.str_14, i32 0, i32 0
  %21 = srem i64 10, 3
  %22 = call i64 @kr_assert_eq(i8* %20, i64 1, i64 %21)
  %23 = getelementptr [4 x i8], [4 x i8]* @.str_15, i32 0, i32 0
  %24 = srem i64 7, 2
  %25 = call i64 @kr_assert_eq(i8* %23, i64 1, i64 %24)
  %26 = getelementptr [4 x i8], [4 x i8]* @.str_16, i32 0, i32 0
  %27 = srem i64 8, 4
  %28 = call i64 @kr_assert_eq(i8* %26, i64 0, i64 %27)
  %29 = getelementptr [5 x i8], [5 x i8]* @.str_17, i32 0, i32 0
  %30 = srem i64 15, 7
  %31 = call i64 @kr_assert_eq(i8* %29, i64 1, i64 %30)
  %32 = getelementptr [18 x i8], [18 x i8]* @.str_18, i32 0, i32 0
  %33 = call i32 @puts(i8* %32)
  store i64 10, i64* %x
  %34 = load i64, i64* %x
  %35 = add i64 %34, 5
  store i64 %35, i64* %x
  %36 = getelementptr [5 x i8], [5 x i8]* @.str_19, i32 0, i32 0
  %37 = load i64, i64* %x
  %38 = call i64 @kr_assert_eq(i8* %36, i64 15, i64 %37)
  %39 = load i64, i64* %x
  %40 = sub i64 %39, 3
  store i64 %40, i64* %x
  %41 = getelementptr [5 x i8], [5 x i8]* @.str_20, i32 0, i32 0
  %42 = load i64, i64* %x
  %43 = call i64 @kr_assert_eq(i8* %41, i64 12, i64 %42)
  %44 = load i64, i64* %x
  %45 = mul i64 %44, 2
  store i64 %45, i64* %x
  %46 = getelementptr [5 x i8], [5 x i8]* @.str_21, i32 0, i32 0
  %47 = load i64, i64* %x
  %48 = call i64 @kr_assert_eq(i8* %46, i64 24, i64 %47)
  %49 = load i64, i64* %x
  %50 = sdiv i64 %49, 4
  store i64 %50, i64* %x
  %51 = getelementptr [5 x i8], [5 x i8]* @.str_22, i32 0, i32 0
  %52 = load i64, i64* %x
  %53 = call i64 @kr_assert_eq(i8* %51, i64 6, i64 %52)
  %54 = load i64, i64* %x
  %55 = srem i64 %54, 4
  store i64 %55, i64* %x
  %56 = getelementptr [5 x i8], [5 x i8]* @.str_23, i32 0, i32 0
  %57 = load i64, i64* %x
  %58 = call i64 @kr_assert_eq(i8* %56, i64 2, i64 %57)
  %59 = getelementptr [14 x i8], [14 x i8]* @.str_24, i32 0, i32 0
  %60 = call i32 @puts(i8* %59)
  store i64 255, i64* %mask
  %61 = getelementptr [3 x i8], [3 x i8]* @.str_25, i32 0, i32 0
  %62 = sub i64 0, 1
  %63 = xor i64 0, -1
  %64 = call i64 @kr_assert_eq(i8* %61, i64 %62, i64 %63)
  %65 = getelementptr [4 x i8], [4 x i8]* @.str_26, i32 0, i32 0
  %66 = xor i64 5, -1
  %67 = xor i64 %66, -1
  %68 = call i64 @kr_assert_eq(i8* %65, i64 5, i64 %67)
  %69 = getelementptr [14 x i8], [14 x i8]* @.str_27, i32 0, i32 0
  %70 = call i32 @puts(i8* %69)
  %71 = getelementptr [6 x i8], [6 x i8]* @.str_28, i32 0, i32 0
  %72 = sub i64 0, 5
  %73 = sub i64 0, %72
  %74 = call i64 @kr_assert_eq(i8* %71, i64 5, i64 %73)
  %75 = getelementptr [7 x i8], [7 x i8]* @.str_29, i32 0, i32 0
  %76 = sub i64 0, 7
  %77 = add i64 3, 4
  %78 = sub i64 0, %77
  %79 = call i64 @kr_assert_eq(i8* %75, i64 %76, i64 %78)
  %80 = getelementptr [11 x i8], [11 x i8]* @.str_30, i32 0, i32 0
  %81 = call i32 @puts(i8* %80)
  %82 = getelementptr [9 x i8], [9 x i8]* @.str_31, i32 0, i32 0
  %83 = shl i64 1, 4
  %84 = or i64 %83, 3
  %85 = call i64 @kr_assert_eq(i8* %82, i64 19, i64 %84)
  %86 = getelementptr [15 x i8], [15 x i8]* @.str_32, i32 0, i32 0
  %87 = and i64 255, 240
  %88 = ashr i64 %87, 4
  %89 = call i64 @kr_assert_eq(i8* %86, i64 15, i64 %88)
  %90 = getelementptr [6 x i8], [6 x i8]* @.str_33, i32 0, i32 0
  %91 = mul i64 3, 2
  %92 = add i64 5, %91
  %93 = call i64 @kr_assert_eq(i8* %90, i64 11, i64 %92)
  %94 = getelementptr [8 x i8], [8 x i8]* @.str_34, i32 0, i32 0
  %95 = add i64 5, 3
  %96 = mul i64 %95, 2
  %97 = call i64 @kr_assert_eq(i8* %94, i64 16, i64 %96)
  %98 = getelementptr [18 x i8], [18 x i8]* @.str_35, i32 0, i32 0
  %99 = call i32 @puts(i8* %98)
  %100 = getelementptr [9 x i8], [9 x i8]* @.str_36, i32 0, i32 0
  %101 = shl i64 1, 3
  %102 = icmp sgt i64 %101, 5
  %103 = call i64 @kr_assert_true(i8* %100, i1 %102)
  %104 = getelementptr [11 x i8], [11 x i8]* @.str_37, i32 0, i32 0
  %105 = ashr i64 16, 2
  %106 = icmp eq i64 %105, 4
  %107 = call i64 @kr_assert_true(i8* %104, i1 %106)
  %108 = getelementptr [1 x i8], [1 x i8]* @.str_38, i32 0, i32 0
  %109 = call i32 @puts(i8* %108)
  %110 = getelementptr [36 x i8], [36 x i8]* @.str_39, i32 0, i32 0
  %111 = call i32 @puts(i8* %110)
  ret i64 0
}

