; Generated by krakenc — Kraken Self-Hosted Compiler
; Source: tests/test_containers.kr

target triple = "x86_64-unknown-linux-gnu"

declare i32 @puts(i8*)
declare i32 @printf(i8*, ...)
declare i64 @strlen(i8*)
declare i8* @malloc(i64)
declare void @free(i8*)
declare i8* @realloc(i8*, i64)
declare i8* @memcpy(i8*, i8*, i64)
declare i32 @memcmp(i8*, i8*, i64)
declare i8* @strcpy(i8*, i8*)
declare i8* @strcat(i8*, i8*)
declare i32 @strcmp(i8*, i8*)
declare i8* @strdup(i8*)
declare i32 @sprintf(i8*, i8*, ...)
declare i32 @snprintf(i8*, i64, i8*, ...)
declare void @exit(i32)
declare i32 @system(i8*)
declare i8* @kr_getenv(i8*)
declare i8* @fopen(i8*, i8*)
declare i32 @fclose(i8*)
declare i64 @fread(i8*, i64, i64, i8*)
declare i64 @fwrite(i8*, i64, i64, i8*)
declare i32 @fputs(i8*, i8*)
declare i64 @fseek(i8*, i64, i32)
declare i64 @ftell(i8*)
declare i64 @atol(i8*)
declare double @atof(i8*)
declare double @sqrt(double)
declare double @pow(double, double)
declare double @floor(double)
declare double @ceil(double)
declare double @fabs(double)

; Kraken runtime functions
declare i8* @kr_str_concat(i8*, i8*)
declare i64 @kr_strlen(i8*)
declare i8* @kr_fmt_int(i64)
declare i8* @kr_fmt_float(double)
declare i8* @kr_fmt_bool(i1)
declare i1 @kr_str_eq(i8*, i8*)
declare i1 @kr_str_ne(i8*, i8*)
declare i8* @kr_str_slice(i8*, i64, i64)
declare i64 @kr_str_index_of(i8*, i8*)
declare i1 @kr_str_contains(i8*, i8*)
declare i1 @kr_str_starts_with(i8*, i8*)
declare i1 @kr_str_ends_with(i8*, i8*)
declare i8* @kr_str_to_lower(i8*)
declare i8* @kr_str_to_upper(i8*)
declare i8* @kr_str_trim(i8*)
declare i64 @kr_str_len(i8*)
declare i8* @kr_str_replace(i8*, i8*, i8*)
declare i64 @kr_atoi(i8*)
declare double @kr_atof(i8*)
declare i8* @kr_from_cstr(i8*)
declare i8* @kr_cstr(i8*)
declare i8* @kr_vec_int_new()
declare void @kr_vec_int_free(i8*)
declare void @kr_vec_int_push(i8*, i64)
declare i64 @kr_vec_int_get(i8*, i64)
declare void @kr_vec_int_set(i8*, i64, i64)
declare i64 @kr_vec_int_len(i8*)
declare i8* @kr_vec_string_new()
declare void @kr_vec_string_free(i8*)
declare void @kr_vec_string_push(i8*, i8*)
declare i8* @kr_vec_string_get(i8*, i64)
declare void @kr_vec_string_set(i8*, i64, i8*)
declare i64 @kr_vec_string_len(i8*)
declare i8* @kr_map_string_string_new()
declare void @kr_map_string_string_free(i8*)
declare void @kr_map_string_string_set(i8*, i8*, i8*)
declare i8* @kr_map_string_string_get(i8*, i8*)
declare i1 @kr_map_string_string_has(i8*, i8*)
declare i8* @kr_map_string_int_new()
declare void @kr_map_string_int_free(i8*)
declare void @kr_map_string_int_set(i8*, i8*, i64)
declare i64 @kr_map_string_int_get(i8*, i8*)
declare i1 @kr_map_string_int_has(i8*, i8*)
declare i64 @kr_detect_host_os()
declare i64 @kr_detect_host_arch()
declare i8* @kr_file_read_string(i8*)
declare i8* @kr_str_split(i8*, i8*)
declare i8* @kr_str_join(i8*, i8*)
declare i64 @kr_str_char_at(i8*, i64)
declare i8* @kr_str_from_char_code(i64)

@.str_0 = private unnamed_addr constant [3 x i8] c"v[\00"
@.str_1 = private unnamed_addr constant [3 x i8] c"]=\00"
@.str_2 = private unnamed_addr constant [6 x i8] c"Alice\00"
@.str_3 = private unnamed_addr constant [4 x i8] c"Bob\00"
@.str_4 = private unnamed_addr constant [8 x i8] c"Charlie\00"
@.str_5 = private unnamed_addr constant [5 x i8] c"len=\00"
@.str_6 = private unnamed_addr constant [10 x i8] c"names[1]=\00"
define i64 @main() {
entry:
  %v = alloca i8*
  %i = alloca i64
  %names = alloca i8*
  %0 = call i8* @kr_vec_int_new()
  store i8* %0, i8** %v
  %1 = load i8*, i8** %v
  %2 = call i64 @kr_vec_int_push(i8* %1, i64 10)
  %3 = load i8*, i8** %v
  %4 = call i64 @kr_vec_int_push(i8* %3, i64 20)
  %5 = load i8*, i8** %v
  %6 = call i64 @kr_vec_int_push(i8* %5, i64 30)
  store i64 0, i64* %i
  br label %while_cond0
while_cond0:
  %7 = load i64, i64* %i
  %8 = icmp slt i64 %7, 3
  br i1 %8, label %while_body1, label %while_exit2
while_body1:
  %9 = getelementptr [3 x i8], [3 x i8]* @.str_0, i32 0, i32 0
  %10 = load i64, i64* %i
  %11 = call i8* @kr_fmt_int(i64 %10)
  %12 = getelementptr [3 x i8], [3 x i8]* @.str_1, i32 0, i32 0
  %13 = load i8*, i8** %v
  %14 = load i64, i64* %i
  %15 = call i64 @kr_vec_int_get(i8* %13, i64 %14)
  %16 = call i8* @kr_fmt_int(i64 %15)
  %17 = call i8* @kr_str_concat(i8* %12, i8* %16)
  %18 = call i8* @kr_str_concat(i8* %11, i8* %17)
  %19 = call i8* @kr_str_concat(i8* %9, i8* %18)
  %20 = call i32 @puts(i8* %19)
  %21 = load i64, i64* %i
  %22 = add i64 %21, 1
  store i64 %22, i64* %i
  br label %while_cond0
while_exit2:
  %23 = call i8* @kr_vec_string_new()
  store i8* %23, i8** %names
  %24 = load i8*, i8** %names
  %25 = getelementptr [6 x i8], [6 x i8]* @.str_2, i32 0, i32 0
  %26 = call i64 @kr_vec_string_push(i8* %24, i8* %25)
  %27 = load i8*, i8** %names
  %28 = getelementptr [4 x i8], [4 x i8]* @.str_3, i32 0, i32 0
  %29 = call i64 @kr_vec_string_push(i8* %27, i8* %28)
  %30 = load i8*, i8** %names
  %31 = getelementptr [8 x i8], [8 x i8]* @.str_4, i32 0, i32 0
  %32 = call i64 @kr_vec_string_push(i8* %30, i8* %31)
  %33 = getelementptr [5 x i8], [5 x i8]* @.str_5, i32 0, i32 0
  %34 = load i8*, i8** %names
  %35 = call i64 @kr_vec_string_len(i8* %34)
  %36 = call i8* @kr_fmt_int(i64 %35)
  %37 = call i8* @kr_str_concat(i8* %33, i8* %36)
  %38 = call i32 @puts(i8* %37)
  %39 = getelementptr [10 x i8], [10 x i8]* @.str_6, i32 0, i32 0
  %40 = load i8*, i8** %names
  %41 = call i8* @kr_vec_string_get(i8* %40, i64 1)
  %42 = call i8* @kr_str_concat(i8* %39, i8* %41)
  %43 = call i32 @puts(i8* %42)
  %44 = load i8*, i8** %v
  %45 = call i64 @kr_vec_int_free(i8* %44)
  %46 = load i8*, i8** %names
  %47 = call i64 @kr_vec_string_free(i8* %46)
  ret i64 0
}

