; Generated by krakenc — Kraken Self-Hosted Compiler
; Source: tests/test_lex_real.kr

target triple = "x86_64-pc-windows-msvc"

declare i32 @puts(i8*)
declare i32 @printf(i8*, ...)
declare i64 @strlen(i8*)
declare i8* @malloc(i64)
declare void @free(i8*)
declare i8* @realloc(i8*, i64)
declare i8* @memcpy(i8*, i8*, i64)
declare i32 @memcmp(i8*, i8*, i64)
declare i8* @strcpy(i8*, i8*)
declare i8* @strcat(i8*, i8*)
declare i32 @strcmp(i8*, i8*)
declare i8* @strdup(i8*)
declare i32 @sprintf(i8*, i8*, ...)
declare i32 @snprintf(i8*, i64, i8*, ...)
declare void @exit(i32)
declare i32 @system(i8*)
declare i8* @kr_getenv(i8*)
declare i8* @fopen(i8*, i8*)
declare i32 @fclose(i8*)
declare i64 @fread(i8*, i64, i64, i8*)
declare i64 @fwrite(i8*, i64, i64, i8*)
declare i32 @fputs(i8*, i8*)
declare i64 @fseek(i8*, i64, i32)
declare i64 @ftell(i8*)
declare i64 @atol(i8*)
declare double @atof(i8*)
declare double @sqrt(double)
declare double @pow(double, double)
declare double @floor(double)
declare double @ceil(double)
declare double @fabs(double)

; Kraken runtime functions
declare i8* @kr_str_concat(i8*, i8*)
declare i64 @kr_strlen(i8*)
declare i8* @kr_fmt_int(i64)
declare i8* @kr_fmt_float(double)
declare i8* @kr_fmt_bool(i1)
declare i1 @kr_str_eq(i8*, i8*)
declare i1 @kr_str_ne(i8*, i8*)
declare i8* @kr_str_slice(i8*, i64, i64)
declare i64 @kr_str_index_of(i8*, i8*)
declare i1 @kr_str_contains(i8*, i8*)
declare i1 @kr_str_starts_with(i8*, i8*)
declare i1 @kr_str_ends_with(i8*, i8*)
declare i8* @kr_str_to_lower(i8*)
declare i8* @kr_str_to_upper(i8*)
declare i8* @kr_str_trim(i8*)
declare i64 @kr_str_len(i8*)
declare i8* @kr_str_replace(i8*, i8*, i8*)
declare i64 @kr_atoi(i8*)
declare double @kr_atof(i8*)
declare i8* @kr_from_cstr(i8*)
declare i8* @kr_cstr(i8*)
declare i8* @kr_vec_int_new()
declare void @kr_vec_int_free(i8*)
declare void @kr_vec_int_push(i8*, i64)
declare i64 @kr_vec_int_get(i8*, i64)
declare void @kr_vec_int_set(i8*, i64, i64)
declare i64 @kr_vec_int_len(i8*)
declare i8* @kr_vec_string_new()
declare void @kr_vec_string_free(i8*)
declare void @kr_vec_string_push(i8*, i8*)
declare i8* @kr_vec_string_get(i8*, i64)
declare void @kr_vec_string_set(i8*, i64, i8*)
declare i64 @kr_vec_string_len(i8*)
declare i8* @kr_map_string_string_new()
declare void @kr_map_string_string_free(i8*)
declare void @kr_map_string_string_set(i8*, i8*, i8*)
declare i8* @kr_map_string_string_get(i8*, i8*)
declare i1 @kr_map_string_string_has(i8*, i8*)
declare i8* @kr_map_string_int_new()
declare void @kr_map_string_int_free(i8*)
declare void @kr_map_string_int_set(i8*, i8*, i64)
declare i64 @kr_map_string_int_get(i8*, i8*)
declare i1 @kr_map_string_int_has(i8*, i8*)
declare i64 @kr_detect_host_os()
declare i64 @kr_detect_host_arch()
declare i8* @kr_file_read_string(i8*)
declare i8* @kr_str_split(i8*, i8*)
declare i8* @kr_str_join(i8*, i8*)
declare i64 @kr_str_char_at(i8*, i64)
declare i8* @kr_str_from_char_code(i64)

@.str_0 = private unnamed_addr constant [18 x i8] c"step 1: read file\00"
@.str_1 = private unnamed_addr constant [19 x i8] c"tests/test_tiny.kr\00"
@.str_2 = private unnamed_addr constant [28 x i8] c"step 2: read complete, len=\00"
@.str_3 = private unnamed_addr constant [9 x i8] c"source: \00"
@.str_4 = private unnamed_addr constant [15 x i8] c"step 3: lexing\00"
@.str_5 = private unnamed_addr constant [26 x i8] c"step 4: tokenized, count=\00"
define i64 @main() {
entry:
  %s = alloca i8*
  %int_data = alloca i8*
  %tok_lexemes = alloca i8*
  %count = alloca i64
  %0 = getelementptr [18 x i8], [18 x i8]* @.str_0, i32 0, i32 0
  %1 = call i32 @puts(i8* %0)
  %2 = getelementptr [19 x i8], [19 x i8]* @.str_1, i32 0, i32 0
  %3 = call i8* @kr_file_read_string(i8* %2)
  store i8* %3, i8** %s
  %4 = getelementptr [28 x i8], [28 x i8]* @.str_2, i32 0, i32 0
  %5 = load i8*, i8** %s
  %6 = call i64 @strlen(i8* %5)
  %7 = call i8* @kr_fmt_int(i64 %6)
  %8 = call i8* @kr_str_concat(i8* %4, i8* %7)
  %9 = call i32 @puts(i8* %8)
  %10 = getelementptr [9 x i8], [9 x i8]* @.str_3, i32 0, i32 0
  %11 = load i8*, i8** %s
  %12 = call i8* @kr_str_concat(i8* %10, i8* %11)
  %13 = call i32 @puts(i8* %12)
  %14 = getelementptr [15 x i8], [15 x i8]* @.str_4, i32 0, i32 0
  %15 = call i32 @puts(i8* %14)
  %16 = call i8* @kr_vec_int_new()
  store i8* %16, i8** %int_data
  %17 = call i8* @kr_vec_string_new()
  store i8* %17, i8** %tok_lexemes
  %18 = load i8*, i8** %s
  %19 = load i8*, i8** %int_data
  %20 = load i8*, i8** %tok_lexemes
  %21 = call i64 @kr_tokenize(i8* %18, i8* %19, i8* %20)
  store i64 %21, i64* %count
  %22 = getelementptr [26 x i8], [26 x i8]* @.str_5, i32 0, i32 0
  %23 = load i64, i64* %count
  %24 = call i8* @kr_fmt_int(i64 %23)
  %25 = call i8* @kr_str_concat(i8* %22, i8* %24)
  %26 = call i32 @puts(i8* %25)
  ret i64 0
}

