; Generated by krakenc — Kraken Self-Hosted Compiler
; Source: tests/test_structs.kr

target triple = "x86_64-unknown-linux-gnu"

declare i32 @puts(i8*)
declare i32 @printf(i8*, ...)
declare i64 @strlen(i8*)
declare i8* @malloc(i64)
declare void @free(i8*)
declare i8* @realloc(i8*, i64)
declare i8* @memcpy(i8*, i8*, i64)
declare i32 @memcmp(i8*, i8*, i64)
declare i8* @strcpy(i8*, i8*)
declare i8* @strcat(i8*, i8*)
declare i32 @strcmp(i8*, i8*)
declare i8* @strdup(i8*)
declare i32 @sprintf(i8*, i8*, ...)
declare i32 @snprintf(i8*, i64, i8*, ...)
declare void @exit(i32)
declare i32 @system(i8*)
declare i8* @kr_getenv(i8*)
declare i8* @fopen(i8*, i8*)
declare i32 @fclose(i8*)
declare i64 @fread(i8*, i64, i64, i8*)
declare i64 @fwrite(i8*, i64, i64, i8*)
declare i32 @fputs(i8*, i8*)
declare i64 @fseek(i8*, i64, i32)
declare i64 @ftell(i8*)
declare i64 @atol(i8*)
declare double @atof(i8*)
declare double @sqrt(double)
declare double @pow(double, double)
declare double @floor(double)
declare double @ceil(double)
declare double @fabs(double)

; Kraken runtime functions
declare i8* @kr_str_concat(i8*, i8*)
declare i64 @kr_strlen(i8*)
declare i8* @kr_fmt_int(i64)
declare i8* @kr_fmt_float(double)
declare i8* @kr_fmt_bool(i1)
declare i1 @kr_str_eq(i8*, i8*)
declare i1 @kr_str_ne(i8*, i8*)
declare i8* @kr_str_slice(i8*, i64, i64)
declare i64 @kr_str_index_of(i8*, i8*)
declare i1 @kr_str_contains(i8*, i8*)
declare i1 @kr_str_starts_with(i8*, i8*)
declare i1 @kr_str_ends_with(i8*, i8*)
declare i8* @kr_str_to_lower(i8*)
declare i8* @kr_str_to_upper(i8*)
declare i8* @kr_str_trim(i8*)
declare i64 @kr_str_len(i8*)
declare i8* @kr_str_replace(i8*, i8*, i8*)
declare i64 @kr_atoi(i8*)
declare double @kr_atof(i8*)
declare i8* @kr_from_cstr(i8*)
declare i8* @kr_cstr(i8*)
declare i8* @kr_vec_int_new()
declare void @kr_vec_int_free(i8*)
declare void @kr_vec_int_push(i8*, i64)
declare i64 @kr_vec_int_get(i8*, i64)
declare void @kr_vec_int_set(i8*, i64, i64)
declare i64 @kr_vec_int_len(i8*)
declare i8* @kr_vec_string_new()
declare void @kr_vec_string_free(i8*)
declare void @kr_vec_string_push(i8*, i8*)
declare i8* @kr_vec_string_get(i8*, i64)
declare void @kr_vec_string_set(i8*, i64, i8*)
declare i64 @kr_vec_string_len(i8*)
declare i8* @kr_map_string_string_new()
declare void @kr_map_string_string_free(i8*)
declare void @kr_map_string_string_set(i8*, i8*, i8*)
declare i8* @kr_map_string_string_get(i8*, i8*)
declare i1 @kr_map_string_string_has(i8*, i8*)
declare i8* @kr_map_string_int_new()
declare void @kr_map_string_int_free(i8*)
declare void @kr_map_string_int_set(i8*, i8*, i64)
declare i64 @kr_map_string_int_get(i8*, i8*)
declare i1 @kr_map_string_int_has(i8*, i8*)
declare i64 @kr_detect_host_os()
declare i64 @kr_detect_host_arch()
declare i8* @kr_file_read_string(i8*)
declare i8* @kr_str_split(i8*, i8*)
declare i8* @kr_str_join(i8*, i8*)
declare i64 @kr_str_char_at(i8*, i64)
declare i8* @kr_str_from_char_code(i64)

@.str_0 = private unnamed_addr constant [3 x i8] c"fn\00"
@.str_1 = private unnamed_addr constant [11 x i8] c"keyword:fn\00"
@.str_2 = private unnamed_addr constant [4 x i8] c"let\00"
@.str_3 = private unnamed_addr constant [12 x i8] c"keyword:let\00"
@.str_4 = private unnamed_addr constant [3 x i8] c"if\00"
@.str_5 = private unnamed_addr constant [11 x i8] c"keyword:if\00"
@.str_6 = private unnamed_addr constant [7 x i8] c"ident:\00"
@.str_7 = private unnamed_addr constant [10 x i8] c"dist_sq: \00"
@.str_8 = private unnamed_addr constant [10 x i8] c"sum(10): \00"
@.str_9 = private unnamed_addr constant [3 x i8] c"fn\00"
@.str_10 = private unnamed_addr constant [4 x i8] c"let\00"
@.str_11 = private unnamed_addr constant [6 x i8] c"hello\00"
@.str_12 = private unnamed_addr constant [3 x i8] c"i=\00"

define i8* @kr_Point_new(i64 %f0.arg, i64 %f1.arg) {
entry:
  %_ptr = call i8* @malloc(i64 16)
  %_gep0 = getelementptr i8, i8* %_ptr, i64 0
  %_bc0 = bitcast i8* %_gep0 to i64*
  store i64 %f0.arg, i64* %_bc0
  %_gep1 = getelementptr i8, i8* %_ptr, i64 8
  %_bc1 = bitcast i8* %_gep1 to i64*
  store i64 %f1.arg, i64* %_bc1
  ret i8* %_ptr
}
define i8* @kr_make_point(i64 %x.arg, i64 %y.arg) {
entry:
  %x = alloca i64
  store i64 %x.arg, i64* %x
  %y = alloca i64
  store i64 %y.arg, i64* %y
  %0 = load i64, i64* %x
  %1 = load i64, i64* %y
  %2 = call i8* @kr_Point_new(i64 %0, i64 %1)
  ret i8* %2
}

define i64 @kr_distance_sq(i8* %p.arg) {
entry:
  %p = alloca i8*
  store i8* %p.arg, i8** %p
  %0 = load i8*, i8** %p
  %1 = getelementptr i8, i8* %0, i64 0
  %2 = bitcast i8* %1 to i64*
  %3 = load i64, i64* %2
  %4 = load i8*, i8** %p
  %5 = getelementptr i8, i8* %4, i64 0
  %6 = bitcast i8* %5 to i64*
  %7 = load i64, i64* %6
  %8 = mul i64 %3, %7
  %9 = load i8*, i8** %p
  %10 = getelementptr i8, i8* %9, i64 8
  %11 = bitcast i8* %10 to i64*
  %12 = load i64, i64* %11
  %13 = load i8*, i8** %p
  %14 = getelementptr i8, i8* %13, i64 8
  %15 = bitcast i8* %14 to i64*
  %16 = load i64, i64* %15
  %17 = mul i64 %12, %16
  %18 = add i64 %8, %17
  ret i64 %18
}

define i64 @kr_count_to(i64 %n.arg) {
entry:
  %n = alloca i64
  store i64 %n.arg, i64* %n
  %sum = alloca i64
  %i = alloca i64
  store i64 0, i64* %sum
  store i64 0, i64* %i
  br label %while_cond0
while_cond0:
  %0 = load i64, i64* %i
  %1 = load i64, i64* %n
  %2 = icmp slt i64 %0, %1
  br i1 %2, label %while_body1, label %while_exit2
while_body1:
  %3 = load i64, i64* %sum
  %4 = load i64, i64* %i
  %5 = add i64 %3, %4
  store i64 %5, i64* %sum
  %6 = load i64, i64* %i
  %7 = add i64 %6, 1
  store i64 %7, i64* %i
  br label %while_cond0
while_exit2:
  %8 = load i64, i64* %sum
  ret i64 %8
}

define i8* @kr_check_keyword(i8* %s.arg) {
entry:
  %s = alloca i8*
  store i8* %s.arg, i8** %s
  %0 = load i8*, i8** %s
  %1 = getelementptr [3 x i8], [3 x i8]* @.str_0, i32 0, i32 0
  %2 = call i1 @kr_str_eq(i8* %0, i8* %1)
  br i1 %2, label %then0, label %else1
then0:
  %3 = getelementptr [11 x i8], [11 x i8]* @.str_1, i32 0, i32 0
  ret i8* %3
else1:
  br label %merge2
merge2:
  %4 = load i8*, i8** %s
  %5 = getelementptr [4 x i8], [4 x i8]* @.str_2, i32 0, i32 0
  %6 = call i1 @kr_str_eq(i8* %4, i8* %5)
  br i1 %6, label %then3, label %else4
then3:
  %7 = getelementptr [12 x i8], [12 x i8]* @.str_3, i32 0, i32 0
  ret i8* %7
else4:
  br label %merge5
merge5:
  %8 = load i8*, i8** %s
  %9 = getelementptr [3 x i8], [3 x i8]* @.str_4, i32 0, i32 0
  %10 = call i1 @kr_str_eq(i8* %8, i8* %9)
  br i1 %10, label %then6, label %else7
then6:
  %11 = getelementptr [11 x i8], [11 x i8]* @.str_5, i32 0, i32 0
  ret i8* %11
else7:
  br label %merge8
merge8:
  %12 = getelementptr [7 x i8], [7 x i8]* @.str_6, i32 0, i32 0
  %13 = load i8*, i8** %s
  %14 = call i8* @kr_str_concat(i8* %12, i8* %13)
  ret i8* %14
}

define i64 @main() {
entry:
  %p = alloca i8*
  %i = alloca i64
  %0 = call i8* @kr_make_point(i64 3, i64 4)
  store i8* %0, i8** %p
  %1 = getelementptr [10 x i8], [10 x i8]* @.str_7, i32 0, i32 0
  %2 = load i8*, i8** %p
  %3 = call i64 @kr_distance_sq(i8* %2)
  %4 = call i8* @kr_fmt_int(i64 %3)
  %5 = call i8* @kr_str_concat(i8* %1, i8* %4)
  %6 = call i32 @puts(i8* %5)
  %7 = getelementptr [10 x i8], [10 x i8]* @.str_8, i32 0, i32 0
  %8 = call i64 @kr_count_to(i64 10)
  %9 = call i8* @kr_fmt_int(i64 %8)
  %10 = call i8* @kr_str_concat(i8* %7, i8* %9)
  %11 = call i32 @puts(i8* %10)
  %12 = getelementptr [3 x i8], [3 x i8]* @.str_9, i32 0, i32 0
  %13 = call i8* @kr_check_keyword(i8* %12)
  %14 = call i32 @puts(i8* %13)
  %15 = getelementptr [4 x i8], [4 x i8]* @.str_10, i32 0, i32 0
  %16 = call i8* @kr_check_keyword(i8* %15)
  %17 = call i32 @puts(i8* %16)
  %18 = getelementptr [6 x i8], [6 x i8]* @.str_11, i32 0, i32 0
  %19 = call i8* @kr_check_keyword(i8* %18)
  %20 = call i32 @puts(i8* %19)
  store i64 0, i64* %i
  br label %for_cond0
for_cond0:
  %21 = load i64, i64* %i
  %22 = icmp slt i64 %21, 3
  br i1 %22, label %for_body1, label %for_exit2
for_body1:
  %23 = getelementptr [3 x i8], [3 x i8]* @.str_12, i32 0, i32 0
  %24 = load i64, i64* %i
  %25 = call i8* @kr_fmt_int(i64 %24)
  %26 = call i8* @kr_str_concat(i8* %23, i8* %25)
  %27 = call i32 @puts(i8* %26)
  %28 = load i64, i64* %i
  %29 = add i64 %28, 1
  store i64 %29, i64* %i
  br label %for_cond0
for_exit2:
  ret i64 0
}

