; Generated by krakenc — Kraken Self-Hosted Compiler
; Source: tests/test_simple.kr

target triple = "x86_64-pc-windows-msvc"

declare i32 @puts(i8*)
declare i32 @printf(i8*, ...)
declare i64 @strlen(i8*)
declare i8* @malloc(i64)
declare void @free(i8*)
declare i8* @realloc(i8*, i64)
declare i8* @memcpy(i8*, i8*, i64)
declare i32 @memcmp(i8*, i8*, i64)
declare i8* @strcpy(i8*, i8*)
declare i8* @strcat(i8*, i8*)
declare i32 @strcmp(i8*, i8*)
declare i8* @strdup(i8*)
declare i32 @sprintf(i8*, i8*, ...)
declare i32 @snprintf(i8*, i64, i8*, ...)
declare void @exit(i32)
declare i32 @system(i8*)
declare i8* @kr_getenv(i8*)
declare i8* @fopen(i8*, i8*)
declare i32 @fclose(i8*)
declare i64 @fread(i8*, i64, i64, i8*)
declare i64 @fwrite(i8*, i64, i64, i8*)
declare i32 @fputs(i8*, i8*)
declare i64 @fseek(i8*, i64, i32)
declare i64 @ftell(i8*)
declare i64 @atol(i8*)
declare double @atof(i8*)
declare double @sqrt(double)
declare double @pow(double, double)
declare double @floor(double)
declare double @ceil(double)
declare double @fabs(double)

; Kraken runtime functions
declare i8* @kr_str_concat(i8*, i8*)
declare i64 @kr_strlen(i8*)
declare i8* @kr_fmt_int(i64)
declare i8* @kr_fmt_float(double)
declare i8* @kr_fmt_bool(i1)
declare i1 @kr_str_eq(i8*, i8*)
declare i1 @kr_str_ne(i8*, i8*)
declare i8* @kr_str_slice(i8*, i64, i64)
declare i64 @kr_str_index_of(i8*, i8*)
declare i1 @kr_str_contains(i8*, i8*)
declare i1 @kr_str_starts_with(i8*, i8*)
declare i1 @kr_str_ends_with(i8*, i8*)
declare i8* @kr_str_to_lower(i8*)
declare i8* @kr_str_to_upper(i8*)
declare i8* @kr_str_trim(i8*)
declare i64 @kr_str_len(i8*)
declare i8* @kr_str_replace(i8*, i8*, i8*)
declare i64 @kr_atoi(i8*)
declare double @kr_atof(i8*)
declare i8* @kr_from_cstr(i8*)
declare i8* @kr_cstr(i8*)
declare i8* @kr_vec_int_new()
declare void @kr_vec_int_free(i8*)
declare void @kr_vec_int_push(i8*, i64)
declare i64 @kr_vec_int_get(i8*, i64)
declare void @kr_vec_int_set(i8*, i64, i64)
declare i64 @kr_vec_int_len(i8*)
declare i8* @kr_vec_string_new()
declare void @kr_vec_string_free(i8*)
declare void @kr_vec_string_push(i8*, i8*)
declare i8* @kr_vec_string_get(i8*, i64)
declare void @kr_vec_string_set(i8*, i64, i8*)
declare i64 @kr_vec_string_len(i8*)
declare i8* @kr_map_string_string_new()
declare void @kr_map_string_string_free(i8*)
declare void @kr_map_string_string_set(i8*, i8*, i8*)
declare i8* @kr_map_string_string_get(i8*, i8*)
declare i1 @kr_map_string_string_has(i8*, i8*)
declare i8* @kr_map_string_int_new()
declare void @kr_map_string_int_free(i8*)
declare void @kr_map_string_int_set(i8*, i8*, i64)
declare i64 @kr_map_string_int_get(i8*, i8*)
declare i1 @kr_map_string_int_has(i8*, i8*)
declare i64 @kr_detect_host_os()
declare i64 @kr_detect_host_arch()
declare i8* @kr_file_read_string(i8*)
declare i8* @kr_str_split(i8*, i8*)
declare i8* @kr_str_join(i8*, i8*)
declare i64 @kr_str_char_at(i8*, i64)
declare i8* @kr_str_from_char_code(i64)

@.str_0 = private unnamed_addr constant [8 x i8] c"Hello, \00"
@.str_1 = private unnamed_addr constant [2 x i8] c"!\00"
@.str_2 = private unnamed_addr constant [9 x i8] c"result: \00"
@.str_3 = private unnamed_addr constant [7 x i8] c"Kraken\00"
@.str_4 = private unnamed_addr constant [9 x i8] c"correct!\00"
@.str_5 = private unnamed_addr constant [7 x i8] c"wrong!\00"
define i64 @kr_add(i64 %a.arg, i64 %b.arg) {
entry:
  %a = alloca i64
  store i64 %a.arg, i64* %a
  %b = alloca i64
  store i64 %b.arg, i64* %b
  %0 = load i64, i64* %a
  %1 = load i64, i64* %b
  %2 = add i64 %0, %1
  ret i64 %2
}

define void @kr_greet(i8* %name.arg) {
entry:
  %name = alloca i8*
  store i8* %name.arg, i8** %name
  %0 = getelementptr [8 x i8], [8 x i8]* @.str_0, i32 0, i32 0
  %1 = load i8*, i8** %name
  %2 = getelementptr [2 x i8], [2 x i8]* @.str_1, i32 0, i32 0
  %3 = call i8* @kr_str_concat(i8* %1, i8* %2)
  %4 = call i8* @kr_str_concat(i8* %0, i8* %3)
  %5 = call i32 @puts(i8* %4)
  ret void
}

define i64 @main() {
entry:
  %x = alloca i64
  %y = alloca i64
  %result = alloca i64
  store i64 10, i64* %x
  store i64 32, i64* %y
  %0 = load i64, i64* %x
  %1 = load i64, i64* %y
  %2 = call i64 @kr_add(i64 %0, i64 %1)
  store i64 %2, i64* %result
  %3 = getelementptr [9 x i8], [9 x i8]* @.str_2, i32 0, i32 0
  %4 = load i64, i64* %result
  %5 = call i8* @kr_fmt_int(i64 %4)
  %6 = call i8* @kr_str_concat(i8* %3, i8* %5)
  %7 = call i32 @puts(i8* %6)
  %8 = getelementptr [7 x i8], [7 x i8]* @.str_3, i32 0, i32 0
  call void @kr_greet(i8* %8)
  %9 = load i64, i64* %result
  %10 = icmp eq i64 %9, 42
  br i1 %10, label %then0, label %else1
then0:
  %11 = getelementptr [9 x i8], [9 x i8]* @.str_4, i32 0, i32 0
  %12 = call i32 @puts(i8* %11)
  br label %merge2
else1:
  %13 = getelementptr [7 x i8], [7 x i8]* @.str_5, i32 0, i32 0
  %14 = call i32 @puts(i8* %13)
  br label %merge2
merge2:
  ret i64 0
}

